spring:
  application:
    name: EnterpriseExpenseManagementSystem

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/trex}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: ${DRIVER_CLASS:org.postgresql.Driver}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: ${JWT_EXP_TIME}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
        debug: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope:
              - openid
              - profile
              - email


frontend:
  url: ${FRONT_END_URL}

oauth2:
  authorizedRedirectPath: ${OAUTH2_REDIRECT_PATH:/oauth2/success}

logging:
  level:
    org:
      springframework:
        security: DEBUG

cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${API_KEY}
  api-secret: ${API_SECRET}
  max-file-size: ${MAX_FILE_SIZE}
