spring:
  application:
    name: EnterpriseExpenseManagementSystem

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: ${DB_DIALECT}

  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: ${JWT_EXP_TIME}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

frontend:
  url: ${FRONT_END_URL}

logging:
  level:
    org:
      springframework:
        security: DEBUG

file:
  upload-dir: uploads/invoices